export default {
  // 用户目录
  userCatalogOS: "/userCatalogOS",
  userCatalogSGM: "/userCatalogSGM",
  userCatalogAD: "/userCatalogAD",
  inviteManagement: "/InviteManagement",
  // 资源管理
  resourceManageAM: "/resourceManageAM",
  resourceManageAI: "/resourceManageAI",
  // Radius配置
  exterCertServiceRadius: "/exterCertServiceRadius",
  // 网络接入服务
  netAccessServiceWAS: "/netAccessServiceWAS",
  netAccessServiceAC: "/netAccessServiceAC",
  netAccessServicePortal: "/netAccessServicePortal",
  netAccessServiceWVM: "/netAccessServiceWVM",
  netAccessServiceWBM: "/netAccessServiceWBM",
  netAccessServiceWNVD: "/netAccessServiceWNVD",
  // 安全管理
  safetyManagementIP: "/safetyManagementIP",
  safetyManagementAL: "/safetyManagementAL",
  safetyManagementLF: "/safetyManagementLF",
  safetyManagementCommand: "/safetyManagementCommand",
  safetyManagementOTP: "/safetyManagementOTP",
  safetyManagementMD: "/safetyManagementMD",
  // 审计报表
  auditReportUA: "/auditReportUA",
  auditReportApp: "/auditReportApp",
  auditReportAdmin: "/auditReportAdmin",
  auditReportWifi: "/auditReportWifi",
  auditReportWireless: "/auditReportWireless",
  auditReportOnlineUsers: "/auditReportOnlineUsers",
  // 系统设置
  systemSetupAdmin: "/systemSetupAdmin",
  systemSetupAP: "/systemSetupAP",
  systemSetupAdminMsg: "/systemSetupAdminMsg",
  systemSetupAdminMail: "/systemSetupAdminMail",
  systemSetupAuthSource: "/systemSetupAuthSource"
};
