export default {
  // 用户目录
  userCatalogOS: "/userCatalogOS",
  userCatalogSGM: "/userCatalogSGM",
  userCatalogRA: "/userCatalogRA",
  userCatalogAD: "/userCatalogAD",
  userCatalogDS: "/userCatalogDS",
  userCatalogWX: "/userCatalogWX",
  inviteManagement: "/InviteManagement",
  // 资源管理
  resourceManageAM: "/resourceManageAM",
  resourceManageDM: "/resourceManageDM",
  // 网络接入服务
  netAccessServiceWAS: "/netAccessServiceWAS",
  netAccessServicePortal: "/netAccessServicePortal",
  netAccessServiceWVM: "/netAccessServiceWVM",
  netAccessServiceWBM: "/netAccessServiceWBM",
  netAccessServiceWNVD: "/netAccessServiceWNVD",
  netAccessServiceWASU: "/netAccessServiceWASU",
  netAccessServiceOU: "/netAccessServiceOU",
  // 安全管理
  safetyManagementSA: "/safetyManagementSA",
  safetyManagementIP: "/safetyManagementIP",
  safetyManagementAL: "/safetyManagementAL",
  safetyManagementLF: "/safetyManagementLF",
  safetyManagementCommand: "/safetyManagementCommand",
  safetyManagementOTP: "/safetyManagementOTP",
  safetyManagementMD: "/safetyManagementMD",
  // 审计报表
  auditReportUA: "/auditReportUA",
  auditReportApp: "/auditReportApp",
  auditReportAdmin: "/auditReportAdmin",
  auditReportWifi: "/auditReportWifi",
  auditReportWireless: "/auditReportWireless",
  auditReportOnlineUsers: "/auditReportOnlineUsers",
  auditReportFacility: "/auditReportFacility",
  // 系统设置
  systemSetupAdmin: "/systemSetupAdmin",
  systemSetupAP: "/systemSetupAP",
  systemSetupAdminMsg: "/systemSetupAdminMsg",
  systemSetupAdminMail: "/systemSetupAdminMail",
  systemSetupAuthSource: "/systemSetupAuthSource",
  systemSetupPageSet: "/systemSetupPageSet",
  systemSetupUserDefined: "/systemSetupUserDefined"
};
