let data1 = [{
  "resourceId": 1,
  "resourceName": "用户目录",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 1,
  "displayType": "1",
  "menuList": [{
    "resourceId": 8,
    "resourceName": "组织结构",
    "resourceUrl": null,
    "parent": 1,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 9,
    "resourceName": "安全组管理",
    "resourceUrl": null,
    "parent": 1,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 10,
    "resourceName": "AD活动目录",
    "resourceUrl": null,
    "parent": 1,
    "displaySort": 3,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 2,
  "resourceName": "资源管理",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 2,
  "displayType": "1",
  "menuList": [{
    "resourceId": 11,
    "resourceName": "应用管理",
    "resourceUrl": null,
    "parent": 2,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 12,
    "resourceName": "应用发布",
    "resourceUrl": null,
    "parent": 2,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 3,
  "resourceName": "外部认证服务",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 3,
  "displayType": "1",
  "menuList": [{
    "resourceId": 13,
    "resourceName": "Radius配置",
    "resourceUrl": null,
    "parent": 3,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 4,
  "resourceName": "网络接入服务",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 4,
  "displayType": "1",
  "menuList": [{
    "resourceId": 14,
    "resourceName": "无线认证策略",
    "resourceUrl": null,
    "parent": 4,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 15,
    "resourceName": "AC配置",
    "resourceUrl": null,
    "parent": 4,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 16,
    "resourceName": "portal设置",
    "resourceUrl": null,
    "parent": 4,
    "displaySort": 3,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 5,
  "resourceName": "安全管理",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 5,
  "displayType": "1",
  "menuList": [{
    "resourceId": 17,
    "resourceName": "身份认证策略",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 18,
    "resourceName": "异常登录设置",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 19,
    "resourceName": "登录失败控制",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 3,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 20,
    "resourceName": "口令管理",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 4,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 21,
    "resourceName": "OTP管理",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 5,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 22,
    "resourceName": "移动设备管理",
    "resourceUrl": null,
    "parent": 5,
    "displaySort": 6,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 6,
  "resourceName": "审计报表",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 6,
  "displayType": "1",
  "menuList": [{
    "resourceId": 23,
    "resourceName": "用户审计",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 24,
    "resourceName": "应用审计",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 25,
    "resourceName": "管理员审计",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 3,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 26,
    "resourceName": "无线访客记录",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 4,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 27,
    "resourceName": "访客登录审计",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 5,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 28,
    "resourceName": "在线用户审计",
    "resourceUrl": null,
    "parent": 6,
    "displaySort": 6,
    "displayType": "2",
    "menuList": null
  }]
}, {
  "resourceId": 7,
  "resourceName": "系统设置",
  "resourceUrl": null,
  "parent": 0,
  "displaySort": 7,
  "displayType": "1",
  "menuList": [{
    "resourceId": 29,
    "resourceName": "管理员设置",
    "resourceUrl": null,
    "parent": 7,
    "displaySort": 1,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 30,
    "resourceName": "账号属性设置",
    "resourceUrl": null,
    "parent": 7,
    "displaySort": 2,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 31,
    "resourceName": "短信验证码设置",
    "resourceUrl": null,
    "parent": 7,
    "displaySort": 3,
    "displayType": "2",
    "menuList": null
  }, {
    "resourceId": 32,
    "resourceName": "邮箱验证码设置",
    "resourceUrl": null,
    "parent": 7,
    "displaySort": 4,
    "displayType": "2",
    "menuList": null
  }]
}];

export default {
  data1
};
